apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'

def envFile = null
def currentDir = rootProject.projectDir
while (currentDir != null) {
    def potentialEnv = new File(currentDir, '.env')
    if (potentialEnv.exists()) {
        envFile = potentialEnv
        break
    }
    currentDir = currentDir.getParentFile()
}

def env = new Properties()
if (envFile != null && envFile.exists()) {
    envFile.withInputStream { instr ->
        env.load(instr)
    }
}

android {
    namespace "com.nullvoid.app"
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.nullvoid.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        
        buildConfigField "String", "FCM_SECRET_KEY", "\"${env.getProperty('FCM_SECRET_KEY', '')}\""
    }

    buildFeatures {
        buildConfig = true
    }
    signingConfigs {
        debug {
            storeFile file('keystore/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation project(':capacitor-android')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "androidx.webkit:webkit:$androidxWebkitVersion"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:$androidxSwipeRefreshLayoutVersion"
    
    // Firebase
    implementation platform('com.google.firebase:firebase-bom:32.3.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'

    implementation "com.google.android.material:material:1.9.0"
    implementation "androidx.core:core-ktx:1.10.1"
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
}
